[package]
name = "fofc-rs"
version = "1.0.0"
edition = "2021"
description = "Binary data format used to encode random files."
authors = ["Benton Johnson <liondadev@gmail.com>"]
license = "MIT"

[dependencies]
byteorder = "1.5.0"
log = "0.4.22"